# Generated by Django 3.2.7 on 2022-11-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=6)),
                ('sex', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pey_method', models.IntegerField()),
                ('state', models.IntegerField()),
                ('submit_date', models.DateTimeField()),
                ('chech_in_date', models.DateTimeField()),
                ('chech_out_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kind', models.IntegerField()),
                ('state', models.BooleanField()),
            ],
        ),
    ]
